v4l2loopback create

diff --git a/v4l2loopback b/v4l2loopback
--- a/v4l2loopback
+++ b/v4l2loopback
@@ -4,6 +4,7 @@ usage() {
     echo "v4l2loopback control script"
     echo "---------------------------"
     echo
+    echo "Usage: $0 create 'gst-spec-1;gst-spec-2;...;gst=spec-n'"
     echo "Usage: $0 set-placeholder image [device]"
     exit 1
 }
@@ -13,10 +14,31 @@ die() {
     exit 1
 }
 
-set_placeholder() {
-    GSTL=`which gst-launch-0.10`
-    [ -x "$GSTL" ] || die "gst-launch executable not found"
+MOD=v4l2loopback
+GSTL=`which gst-launch-0.10`
+[ -x "$GSTL" ] || die "gst-launch executable not found"
 
+
+create() {
+    sudo rmmod $MOD
+    lsmod | grep -q $MOD && die "can't remove module"
+    last=`ls /dev/video* | tail -n 1 | sed 's!/dev/video\(.*\)!\1!'`
+    [ -z "$last" ] && last=0
+    specs=`echo "$1" | sed 's/;/\n/g'`
+    count=`echo "$specs" | wc -l`
+    numbers=`seq $(($last+1)) $(($last+$count))`
+    sudo modprobe $MOD video_nr=`echo $numbers | tr ' ' ','`
+    i=$(($last+1))
+    for spec in $specs; do
+        echo "Init /dev/video$i"
+        echo 1 | sudo tee /sys/devices/virtual/video4linux/video$i/keep_format > /dev/null
+        echo "$GSTL videotestsrc num-buffers=1 ! "$spec" ! v4l2sink device=/dev/video$i"
+        $GSTL videotestsrc num-buffers=1 ! "$spec" ! v4l2sink device=/dev/video$i
+        i=$(($i+1))
+    done
+}
+
+set_placeholder() {
     LOOPBACK_IO="`dirname $(which $0)`/v4l2loopback_io"
     [ -x "$LOOPBACK_IO" ] || die "v4l2loopback_io executable not found"
 
@@ -57,6 +79,9 @@ set_placeholder() {
 command="$1"
 shift
 case "$command" in
+    "create")
+        create $@
+        ;;
     "set-placeholder")
         set_placeholder $@
         ;;
