when dying, write to stderr

diff --git a/utils/v4l2loopback-ctl b/utils/v4l2loopback-ctl
--- a/utils/v4l2loopback-ctl
+++ b/utils/v4l2loopback-ctl
@@ -21,7 +21,7 @@ Arguments:
 }
 
 die() {
-    echo $1
+    echo "$@" 1>&2
     exit 1
 }
 
@@ -34,6 +34,10 @@ parse_device() {
         die "can't parse device"
     fi
     sysfs=/sys/devices/virtual/video4linux/${device##*/}
+}
+
+check_gstreamer() {
+ which gst-launch-0.10 > /dev/null || die "can't find gstreamer"
 }
 
 
