warning about disabled timeout when setting image

diff --git a/utils/v4l2loopback-ctl b/utils/v4l2loopback-ctl
--- a/utils/v4l2loopback-ctl
+++ b/utils/v4l2loopback-ctl
@@ -123,6 +123,13 @@ set_timeout_image() {
         echo "Reading from $uri"
         gst-launch-0.10 uridecodebin uri=$uri ! ffmpegcolorspace ! videoscale ! imagefreeze ! identity error-after=2 ! v4l2sink show-preroll-frame=false device=/dev/video0
     fi
+    timeout=`v4l2-ctl -d $device -C timeout | sed -n 's/^timeout: //p'`
+    [ -n "$timeout" ] || die "couldn't get timeout"
+    echo "timeout: $timeout"
+    [ "$timeout" = 0 ] && {
+        echo 'Timeout is currently disabled; you can set it to some positive value, e.g.:'
+        echo "$ v4l2-ctl -d $device -c timeout=3000"
+    }
 }
 
 command="$1"
