v4l2loopback-ctl set-fps

diff --git a/utils/v4l2loopback-ctl b/utils/v4l2loopback-ctl
--- a/utils/v4l2loopback-ctl
+++ b/utils/v4l2loopback-ctl
@@ -3,6 +3,8 @@
 usage() {
     cat <<!
 Usage:
+    $0 set-fps FPS /dev/videoX
+            Set device fps (if format is already negotiated)
     $0 set-timeout-image IMAGE /dev/videoX
             Set timeout on device, and optionally the placeholder picture,
             instead of default null frame
@@ -34,6 +36,15 @@ parse_device() {
     sysfs=/sys/devices/virtual/video4linux/${device##*/}
 }
 
+
+set_fps() {
+    fps="$1"
+    parse_device "$2"
+    [ -z "$fps" ] && usage
+
+    echo "@$fps" | sudo tee "$sysfs/format" >/dev/null || die "Set fps failed"
+    echo OK
+}
 
 set_caps() {
     caps="$1"
@@ -88,6 +99,9 @@ set_timeout_image() {
 command="$1"
 shift
 case "$command" in
+    "set-fps")
+        set_fps "$@"
+        ;;
     "set-caps")
         set_caps "$@"
         ;;
